CREATE TABLE course (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY,
	advising_requisite_code		VARCHAR(255),
	core_literature_requirement VARCHAR(255),
	course_catalog_text			VARCHAR(255),
	course_code					INTEGER,
	course_code_number			INTEGER,
	course_code_prefix			VARCHAR(255),
	course_code_sanitized		VARCHAR(255),
	course_fees					INTEGER,
	course_title				VARCHAR(255),
	default_credit_hours		VARCHAR(255),
	division_code				VARCHAR(255),
	fee_type					VARCHAR(255),
	fixed_variable_credit		INTEGER,
	max_credit_hours			INTEGER,
	min_credit_hourse			INTEGER,
	PRIMARY KEY (id)



);